/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package logikcull.loadfiles

class App {
    fun parse(pathname: String): Loadfile {
        return Loadfile.from(pathname)
    }
}

fun main(args: Array<String>) {
    if (args.isEmpty()) {
        System.err.println("usage: gradle run --args 'path/to/loadfile1.opt path/to/loadfile2.opt'")
    }

    for (path in args) {
        try {
            App().parse(path).use { loadfile ->
                println("| Loadfile: %-66s |\n".format(path))
                println("| Control Number      | Volume              | Path                             |")
                println("| ------------------- | ------------------- | -------------------------------- |")
                for (entry in loadfile.entries) {
                    println("| %-19s | %-19s | %-32s |\n".format(entry.controlNumber, entry.volumeName, entry.path))
                }

                val validatorResult = loadfile.validate()
                println("| Loadfile is valid: ${validatorResult.isValid()}")

                if(!validatorResult.isValid()) {
                    println("| Invalid Entries: ")
                    for(entry in validatorResult.invalidEntries) {
                        println("| %-19s | %-19s | %-32s |\n".format(entry.controlNumber, entry.volumeName, entry.path))
                    }
                }

                println("")
            }
        } catch (e: Exception) {
            e.printStackTrace(System.err)
        }
    }
}
